require: 
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'codebreaker.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/codebreaker/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/codebreaker/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
